--G1_23BCS12775_Divij_Mahajan_Session2
CREATE OR REPLACE FUNCTION NthHighestSalary(N INT) RETURNS TABLE (Salary INT) AS $$
BEGIN
 IF N<1 THEN
 RETURN ;
 END IF;
 RETURN QUERY(
 SELECT DISTINCT E.SALARY FROM EMPLOYEE E
 ORDER BY E.SALARY DESC OFFSET N-1 LIMIT 1
 );
END;
$$ LANGUAGE plpgsql;
