--G1_23BCS12775_Divij_Mahajan_Session4
with c as (
    select CUSTOMER_ID,MIN(ORDER_DATE) AS ORDER_DATE,MIN(customer_pref_delivery_date) AS CUST_DATE FROM DELIVERY
    GROUP BY CUSTOMER_ID HAVING MIN(ORDER_DATE)=MIN(customer_pref_delivery_date)
)
SELECT CAST(
(SELECT COUNT(CUSTOMER_ID) FROM C)*100.0/(SELECT COUNT(DISTINCT CUSTOMER_ID) FROM DELIVERY) AS DECIMAL(10,2) )AS immediate_percentage;

